export const RU = {
    signIn: "войти",
    signingIn:"Signing in...",

    superAdminLogin:"Super Admin Login",

    createAccount: "зарегистрироваться",
    username: "Username",

    email: 'электронное письмо',
    password: 'пароль',
    showPassword: 'показать пароль',
    forgotPassword: 'Забыли пароль?',
    wrongCreds: 'Неправильный адрес электронной почты/пароль',
    hello: 'Привет',
    registeredEmail: "зарегистрированная электронная почта",
    registeredPhone: "зарегистрированный телефон",
    onboardingAppSubmittedMsg: "Ваша заявка отправлена на рассмотрение",
    dashboard: "щиток приборов",
    profile: "профиль",
    wallet: 'бумажник',
    trading: 'торговля',
    settings: 'настройки',
    walletBalance: "баланс кошелька",
    credit: 'кредит',
    transactions: 'сделки',
    allTransactions: "Все транзакции",
    processing: "обработка",
    cancel: "Отмена",
    cancelled: "отменен",
    approve: "утвердить",
    reject: "отклонять",
    submitForApproval: "отправить на утверждение",
    applicationForwarded: "заявка отправлена",
    assign: "назначать",
    assignTo: "назначить на",
    assigned: "назначенный",
    assignedTo: "назначен на",
    pageNotFoundMsg: "страница, которую вы ищете, не существует",
    somethingWentWrongMsg: "что-то пошло не так",
    group: "группа",
    groupName: "имя группы",
    price: "цена",
    symbol: "условное обозначение",
    type: "тип",
    lotSize: "объем партии",
    initiated: "инициированный",
    initiatedOn: "инициировано",
    dividendSplit: "разделение дивидендов",
    split: "расколоть",
    wait: "ждать",
    automations: "Automations",
    userRoles: "User Roles",
    approvalStages: "Approval Stages",
    feeGroups: "Fee Groups",
    securities: "Securities",
    regFields: "Registration Fields",
    label: "Label",
    enable: "Enable",
    enabled: "Enabled",
    required: "Required",
    conditional: "Conditional",
    section: "Section",
    sections: "Sections",
    aboutYou: "About You",
    accountSetup: "Account Setup",
    personalDetails: "Personal Details",
    taxInfo: "Tax Information",
    employmentDetails: "Employement Details",
    tradingExp: "Trading Experience",
    declaration: "Declaration",
    addNewSection: "Add New Section",
    addNewField: "Add New Field",
    confirmDelete: "Are you sure you want to delete this item?",


    approved: "одобренный",
    rejected: "отклоненный",
    txnRef: "ссылка на транзакцию",
    txnRefPlaceholder: "введите ссылку на транзакцию",
    amountDepositPlaceholder: "введите сумму для депозита",
    amountWithdrawPlaceholder: "введите сумму для вывода",
    selectAccount: "выберите аккаунт",
    bankStatement: "выписка из банка",
    bankTxnRef: "справка о банковской операции",
    bankTransfer: "банковский перевод",
    creditDebitCard: "Кредитная / дебетовая карта",
    depositMethod: "метод депозита",
    depositMoney: "внести деньги",
    submitRequest: "Отправить запрос",
    viewHistory: "Посмотреть историю",
    openPositions: "открытые позиции",
    environment: "среда",
    currency: "валюта",
    balance: "остаток средств",
    leverage: "использовать",
    credit: "кредит",
    equity: "беспристрастность",
    margin: "прибыль",
    marginLevel: "уровень маржи",
    freeMargin: "свободная маржа",
    demo: "демо",
    live: "жить",
    noDataAvailable: "данные недоступны",
    noRows: "нет строк",
    execute: "Execute",
    executed: "Executed",
    clients: "Clients",
    notification: "Notifications",
    language: "Language",
    changeLanguage: "Change language",
    rowsPerPage: "Rows per page",


    next: "Next",
    users: "Users",
    fundings: "Fundings",
    dividends: "Dividends",
    finances: "Finances",
    creditRequests: "Credit Requests",
    logout: "выйти",
    deposit: "депозит",
    withdraw: 'отзывать',
    deposits: "депозиты",
    withdrawals: "снятие средств",

    accountType: "Account Type",
    accountId: "Account Id",
    phone: "Phone",
    status: "положение дел",
    regDate: "Registration Date",
    history: "History",
    action: "действия",
    view: "View",
    viewDetails: "View Details",
    date: "датировать",
    amount: "количество",
    account: "учетная запись",
    name: "Name",
    type:""


}